---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
implicit:
  - Магазин является SPA-приложением
  - На странице товара и в каталоге должно выводиться название, рейтинг, цена со скидкой и без нее
  - Пользователь может оформить заказ с переходом на страницу оплаты
  - Пользователь может удалить товар из корзины
  - Пользователь может очистить корзину полностью
  - Пользователь может добавить товар в корзину и продолжать выбирать товары в каталоге
  - Корзина должна храниться в сессии браузера
  - В карточке товара рядом с его количеством должно быть написано слово "штук" или "штука"
  - После нажатия на кнопку "В корзину" появляется модальное окно с выбором количества этого товара
  - После нажатия на кнопку "Удалить" или "Очистить корзину" появляется модальное окно с подтверждением действия
  - Рейтинг товара должен иметь вид "x.xx ★ из 5 ★"
  - При авторизации добавление товара в корзину или его удаление на одной вкладке должно отображаться и на другой
  - После успешного заказа корзина должна очищаться
  - Изображения товара можно просматривать и листать
  - Можно выбирать несколько категорий одновременно для фильтра
  - Среди категорий товара можно выбрать "Не выбрано"
  - В поле ввода для цены в фильтре можно вводить только положительные числа
  - Возможность ввода максимальной цены в фильтре ограничивается актуальной максимальной ценой существующего товара
  - При выборе категории товара для фильтрации сразу высвечивается список всех категорий
  - Если пользователь использовал фильтр, то переходе с одного компоненты SPA на другой он должен сохраниться
  - В выпадающем списке кнопки "Язык" в навигационном меню должны быть только названия языков
  - Сервер должен корректно обрабатывать (статус 200 ОК) запросы браузера
  - Ссылки в навигационном меню должны выделяться при наведении курсора
  - Первая страница со списком товаров для покупки не должна иметь кнопку "Предыдущая"
  - При перелистывании на следующую страницу в списке товаров для покупки происходит автоматическое возвращение к началу страницы
